### ISSUE TITLE
BADONION configuration fix

### ISSUE THREAD

**Issue by smarek** [badonions/tor-login-faker#1]
Hello,

I've found my tor exit-node listed on http://badonions.se/
I do not intentionally run fake or wrongly configured tor exit node, and that surprised me.

Is there any advisory on how to properly fix configuration of tor-node so it's not "bad" ?
I'd like to fix the service I believed I was serving for greater good.

Thank you

**Comment by wille** [comment]
I didn't even know the site existed

Your node is listed under "all nodes" and isn't listed as a bad one. No worries.

**Comment by smarek** [comment]
Well sorry for the buzz then :) :+1:
